language: ruby

rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0

after_script: bundle exec rake coveralls:push

env:
  global:
    - COVERALLS_REPO_TOKEN=X5ZWSPW8VW2JXNJO0qNjlZCQNW4ju89gb
  matrix:
    - AR=4.2.10
    - AR=5.0.6
    - AR=5.1.5
    - AR=5.2.0
    - AR=6.0.0
    - AR=6.1.0
    - AR=latest
    - AR=4.2.10 COMPAT=1
    - AR=5.0.6 COMPAT=1
    - AR=5.1.5 COMPAT=1
    - AR=5.2.0 COMPAT=1
    - AR=6.0.0 COMPAT=1
    - AR=6.1.0 COMPAT=1
    - AR=latest COMPAT=1
